#spring.application.name=sailotech-gateway
#server.port=8181
#eureka.client.service-url.default-zone=http://localhost:8761/eureka
#spring.cloud.gateway.routes.id=employee_route
#spring.cloud.gateway.routes.uri=http://localhost:7171/
#spring.cloud.gateway.routes.predicates.path=/employee/**
#spring.cloud.gateway.routes.id=project_route
#spring.cloud.gateway.routes.uri=http://localhost:7172/project/get?projectID=ST-INT-369
#spring.cloud.gateway.routes.predicates.path=/project/**
#spring.cloud.gateway.routes.id=payroll_route
#spring.cloud.gateway.routes.uri=
#spring.cloud.gateway.routes.predicates=
server:
  port: 8181
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
spring:
  application:
    name: sailotech-gateway
  cloud:
    gateway:
      routes:
      - id: employee_route
        uri: lb://sailotech-employee
        predicates:
        - Path=/employee/**
      - id: project_route
        uri: lb://sailotech-projects
        predicates:
        - Path=/project/**
